Feat/prisma psql
london-codeworks-thesis/spot pull request #26
Opened 2024-05-08 19:12 UTC by jasnwng

2024-05-09 07:20 UTC, SunnyAnter submitted a review, later dismissed

2024-05-09 09:16 UTC, TobyDS requested changes

2024-05-09 09:16 UTC, TobyDS commented on .env.local.template
> +
Remove empty space

2024-05-09 09:16 UTC, TobyDS commented on app/api/db/route.ts
> +    },
Move mock data to a separate file, ideally in a `/data` folder

2024-05-09 09:16 UTC, TobyDS commented on app/dashboard/db/page.tsx
> +  const res = await fetch('http://localhost:3000/api/db');
Make the base URL read from an environment variable

2024-05-09 09:16 UTC, TobyDS commented on app/lib/prisma.ts
> +// const prisma = new PrismaClient();
Remove dead code

2024-05-09 09:16 UTC, TobyDS commented on app/api/route.ts
Empty file should not be included in pull request

2024-05-09 09:16 UTC, TobyDS commented on prisma/schema.prisma
> +// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init
Remove

2024-05-11 18:09 UTC, TobyDS submitted a review, later dismissed

2024-05-13 08:45 UTC, TobyDS approved these changes

2024-05-13 08:46 UTC, SunnyAnter approved these changes

2024-05-13 08:46 UTC, merged